/*
 * MessagesLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.messagemedia.api;

import com.messagemedia.api.controllers.*;
import com.messagemedia.api.http.client.HttpClient;

public class MessagesClient {
    /**
     * Singleton access to Messages controller
     * @return	Returns the MessagesController instance 
     */
    public MessagesController getMessages() {
        return MessagesController.getInstance();
    }

    /**
     * Singleton access to DeliveryReports controller
     * @return	Returns the DeliveryReportsController instance 
     */
    public DeliveryReportsController getDeliveryReports() {
        return DeliveryReportsController.getInstance();
    }

    /**
     * Singleton access to Replies controller
     * @return	Returns the RepliesController instance 
     */
    public RepliesController getReplies() {
        return RepliesController.getInstance();
    }

    /**
     * Get the shared http client currently being used for API calls
     * @return The http client instance currently being used
     */
    public HttpClient getSharedHttpClient() {
        return BaseController.getClientInstance();
    }
    
    /**
     * Set a shared http client to be used for API calls
     * @param httpClient The http client to use
     */
    public void setSharedHttpClient(HttpClient httpClient) {
        BaseController.setClientInstance(httpClient);
    }

    /**
     * Default constructor 
     */     
    public MessagesClient() {
    }

}